---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fralex-life
  namespace: fralex-life
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.fralex-life: glob:bigday-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fralex-life
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fralex-life
    spec:
      containers:
      - args:
        - site
        command:
        - serve
        image: shimmerjs/fralex.life:bigday-6a5f3e7db1d58dcf6ea409dbc8524f6557334f0f
        imagePullPolicy: Always
        name: fralex-life
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /site/serve.json
          name: fralex-life
          subPath: serve.json
      volumes:
      - configMap:
          name: fralex-life
        name: fralex-life
