---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fralex-life
  namespace: fralex-life
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.fralex-life: glob:bigday-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fralex-life
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fralex-life
    spec:
      containers:
      - image: shimmerjs/fralex.life:bigday-68e3a27f0780d66f7f9e48f255a28281e5470d99
        imagePullPolicy: Always
        name: fralex-life
        ports:
        - containerPort: 5000
